const PT_SPOKEN = {
  ABOBORA: "abóbora",
  AGUA: "água",
  AGUIA: "águia",
  ALIENIGENA: "alienígena",
  AMANHA: "amanhã",
  AMBULANCIA: "ambulância",
  ANCORA: "âncora",
  ARBITRO: "árbitro",
  ARCOIRIS: "arco-íris",
  ARMARIO: "armário",
  ARQUIPELAGO: "arquipélago",
  ARVORE: "árvore",
  AVO: "avó",
  AVOO: "avô",
  BACTERIA: "bactéria",
  BEBE: "bebê",
  BIOLUMINESCENCIA: "bioluminescência",
  BONE: "boné",
  BRACO: "braço",
  CABECA: "cabeça",
  CAFE: "café",
  CALCA: "calça",
  CALENDARIO: "calendário",
  CANCAO: "canção",
  CEREBRO: "cérebro",
  CHAPEU: "chapéu",
  CIUME: "ciúme",
  CONSTELACAO: "constelação",
  CORACAO: "coração",
  CORRENTE_MARITIMA: "corrente marítima",
  "CORRENTE MARITIMA": "corrente marítima",
  CRANIO: "crânio",
  CRONOMETRO: "cronômetro",
  DANCA: "dança",
  DECADA: "década",
  DICIONARIO: "dicionário",
  DIPLOMATICO: "diplomático",
  DIRIGIVEL: "dirigível",
  DUZIA: "dúzia",
  EQUINOCIO: "equinócio",
  ESPERANCA: "esperança",
  ESTACAO: "estação",
  ESTETOSCOPIO: "estetoscópio",
  ESTOMAGO: "estômago",
  EXERCICIO: "exercício",
  FAISCA: "faísca",
  FAMILIA: "família",
  FARMACEUTICO: "farmacêutico",
  FARMACIA: "farmácia",
  FIGADO: "fígado",
  FOTOGRAFO: "fotógrafo",
  FOTOSSINTESE: "fotossíntese",
  FRACAO: "fração",
  FUMACA: "fumaça",
  "FUSO HORARIO": "fuso horário",
  GALAXIA: "galáxia",
  GEMEO: "gêmeo",
  GINASTICA: "ginástica",
  HAMBURGUER: "hambúrguer",
  HELICOPTERO: "helicóptero",
  HEMISFERIO: "hemisfério",
  HIPOPOTAMO: "hipopótamo",
  HISTORIA: "história",
  IRMA: "irmã",
  JACARE: "jacaré",
  JUPITER: "júpiter",
  LABORATORIO: "laboratório",
  LAMPADA: "lâmpada",
  LAPIS: "lápis",
  LIBELULA: "libélula",
  LILAS: "lilás",
  LINGUA: "língua",
  MACA: "maçã",
  MAE: "mãe",
  MANHA: "manhã",
  MARE: "maré",
  MECANICO: "mecânico",
  MEDICO: "médico",
  MERCURIO: "mercúrio",
  MES: "mês",
  MICROSCOPIO: "microscópio",
  MIGRACAO: "migração",
  MONCAO: "monção",
  MUSCULO: "músculo",
  MUSICA: "música",
  NATACAO: "natação",
  NEVOA: "névoa",
  NIVEL: "nível",
  ONIBUS: "ônibus",
  ORBITA: "órbita",
  OXIGENIO: "oxigênio",
  PA: "pá",
  PACIENCIA: "paciência",
  PAIS: "país",
  PANTANO: "pântano",
  PASSARO: "pássaro",
  PE: "pé",
  PENINSULA: "península",
  PESCOCO: "pescoço",
  PESSEGO: "pêssego",
  PLANCTON: "plâncton",
  PLANICIE: "planície",
  PRACA: "praça",
  PREGUICA: "preguiça",
  PROTEINA: "proteína",
  PSICOLOGO: "psicólogo",
  REGUA: "régua",
  RELAMPAGO: "relâmpago",
  RELOGIO: "relógio",
  REMEDIO: "remédio",
  SANDALIA: "sandália",
  SANDUICHE: "sanduíche",
  SATELITE: "satélite",
  SECULO: "século",
  SOFA: "sofá",
  SOLSTICIO: "solstício",
  SUETER: "suéter",
  TAXI: "táxi",
  TECTONICA: "tectônica",
  TELESCOPIO: "telescópio",
  TENIS: "tênis",
  TRES: "três",
  TROFEU: "troféu",
  TROPICO: "trópico",
  VENUS: "vênus",
  VETERINARIO: "veterinário",
  VOLEI: "vôlei",
};

export function ptSpeakable(word) {
  if (!word) return "";
  const key = word.toUpperCase();
  if (PT_SPOKEN[key]) return PT_SPOKEN[key];
  if (/AO$/.test(key)) return (key.slice(0, -2) + "ÃO").toLowerCase();
  if (/OES$/.test(key)) return (key.slice(0, -3) + "ÕES").toLowerCase();
  if (/AES$/.test(key)) return (key.slice(0, -3) + "ÃES").toLowerCase();
  return word.toLowerCase();
}

export function speakable(word, lang) {
  return lang === "pt" ? ptSpeakable(word) : (word || "").toLowerCase();
}
